// Global usings shared across all LanSpire source files.
// Reduces boilerplate using-blocks in partial class files.
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Buffers.Binary;
global using Godot;
global using HarmonyLib;
global using MegaCrit.Sts2.Core.Entities.Multiplayer;
global using MegaCrit.Sts2.Core.Helpers;
global using MegaCrit.Sts2.Core.Modding;
global using MegaCrit.Sts2.Core.Multiplayer;
global using MegaCrit.Sts2.Core.Multiplayer.Connection;
global using MegaCrit.Sts2.Core.Multiplayer.Game;
global using MegaCrit.Sts2.Core.Multiplayer.Messages.Game;
global using MegaCrit.Sts2.Core.Multiplayer.Messages.Game.Checksums;
global using MegaCrit.Sts2.Core.Multiplayer.Messages.Game.Flavor;
global using MegaCrit.Sts2.Core.Multiplayer.Messages.Game.Sync;
global using MegaCrit.Sts2.Core.Multiplayer.Messages.Lobby;
global using MegaCrit.Sts2.Core.Multiplayer.Messages;
global using MegaCrit.Sts2.Core.Multiplayer.Serialization;
global using MegaCrit.Sts2.Core.Nodes;
global using MegaCrit.Sts2.Core.Nodes.CommonUi;
global using MegaCrit.Sts2.Core.Nodes.Screens.MainMenu;
global using MegaCrit.Sts2.addons.mega_text;
global using MegaCrit.Sts2.Core.Nodes.GodotExtensions;
global using MegaCrit.Sts2.Core.Platform;
global using MegaCrit.Sts2.Core.Platform.Null;
global using MegaCrit.Sts2.Core.Runs;
global using MegaCrit.Sts2.Core.Saves;

global using MegaCrit.Sts2.Core.Nodes.Multiplayer;
global using MegaCrit.Sts2.Core.GameActions;
global using MegaCrit.Sts2.Core.GameActions.Multiplayer;
global using MegaCrit.Sts2.Core.Entities.Models;
global using MegaCrit.Sts2.Core.Combat;
global using MegaCrit.Sts2.Core.Entities.Players;
global using MegaCrit.Sts2.Core.Multiplayer.Game.Lobby;
global using LanSpire.Helpers;
global using LanSpire.Localization;
global using LanSpire.Components;
global using static LanSpire.Components.UiHelpers;
global using static LanSpire.Helpers.NetworkHelpers;
